### PR TITLE
Ensure SKU is not 0 when tracking ecommerce items

### LINKED ISSUE #37: You must specify a SKU for the Ecommerce item
Hi,

When generating some visitors, I randomly got this exception:
```
  [Exception]                                    
  You must specify a SKU for the Ecommerce item  
```

I guess this was just bad luck, but I know too little about Ecommerce to find the source and just wanted to document it here.

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #37

### CODE REVIEW

File: Generator/VisitsFake.php [hunk 1]
```diff
@@ -143,7 +143,7 @@ public function generate($time = false, $idSite = 1, $limit = 1000)
                 $price =  $this->faker->randomNumber(2);
                 $quantity = $this->faker->numberBetween(1,4);
 
-                $tracker->addEcommerceItem($sku = $this->faker->randomNumber(4), $this->faker->productName, 'Music Category', $price, $quantity);
+                $tracker->addEcommerceItem($sku = $this->faker->randomNumber(1, 9999), $this->faker->productName, 'Music Category', $price, $quantity);
```
Comment (sgiehl) [inline Generator/VisitsFake.php]: `randomNumber(4)` creates a random number between `0` and `9999` (up to 4 digits), but as `0` is an invalid sku value, we need to ensure it's at least `1`
